[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.4", features = ["multipart", "ws"] }
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
tower-http = { version = "0.6.6", features = ["cors"] }

# ğŸ‘‡ SQLx mit Postgres + Migrations
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-rustls", "macros", "time"] }
dotenvy = "0.15.7"

# ğŸ” Sicherheit & Auth
diesel = { version = "2.3.2", features = ["postgres","r2d2", "chrono"] }
r2d2 = "0.8.10"
bcrypt = "0.17.1"
chrono = { version = "0.4.42", features = ["serde"] }

uuid = { version = "1.18.1", features = ["v4"] }
sha2 = "0.10.9"

jsonwebtoken = "9.3.1"

futures-util = "0.3.31"